# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a79f8cb9f578727611b29946152febe5ba07c303e59096a4bac089d6d2c32f2ae14f023ee8f026aa9fde1a31d599956ef742770744d3a6773dc86c6f8e2955a

test:
  secret_key_base: 9c3aef8e161df08512d2468c6852cac87767db5cc645204fc80215d927ae52dafbbb5e6509e36d6b95443be12a4000205c00f8a9ca94b9d57c09a84fe6ac31eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
